version: "3"

services:

  nginx:
    image: nginx:1.23.0
    restart: always
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx:/etc/nginx/conf.d:ro
      - ./log:/var/log/nginx
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    build: ./api
    restart: always
    volumes:
      - ./models:/api/models
